# Paths to ignore during linting.
excluded:
  - fastlane
  - Localization
  - Pods

# See all available rules with 'swiftlint rules' or 'swiftlint generate-docs > swiftlint-docs.md'.
opt_in_rules:
  # - empty_count
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_string
  - force_unwrapping
  - let_var_whitespace
  - redundant_nil_coalescing
  - yoda_condition

disabled_rules:
  # - todo
  - identifier_name # Example: Variable name should only contain alphanumeric characters: 'fileName_01'
  - function_body_length
  - type_body_length
  - trailing_comma

cyclomatic_complexity:
  ignores_case_statements: true

line_length:
  warning: 140
  error: 220
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 40
  error: 100

vertical_whitespace:
  severity: warning
  max_empty_lines: 3

# Set output type.
reporter: "xcode"
