# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Multiplatform Redux Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #pod 'dreiKit', :path => '../../../dreiKit'
  pod 'dreiKit', :git => 'https://github.com/dreipol/dreiKit', :tag => '1.0.7'
  pod 'shared', :path => '../../shared'
  pod 'lottie-ios'
  pod 'Firebase/Crashlytics', '~> 7.6.0'
  pod 'Firebase/Analytics', '~> 7.6.0'
  pod 'MaterialComponents/Chips', '~> 123.0.0'

  target 'Multiplatform Redux SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Multiplatform Redux SampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
